CREATE TABLE tbooker.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL CHECK (btrim(name) <> ''),
    email VARCHAR(254) NOT NULL CHECK (btrim(email) <> '')
);
CREATE UNIQUE INDEX uq_users_email ON tbooker.users (lower(email));

CREATE TABLE tbooker.movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL CHECK (btrim(title) <> ''),
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0)
);

CREATE TABLE tbooker.theatres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL CHECK (btrim(name) <> ''),
    city VARCHAR(120) NOT NULL CHECK (btrim(city) <> '')
);

CREATE TABLE tbooker.screens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theatre_id BIGINT NOT NULL REFERENCES tbooker.theatres (id),
    name VARCHAR(100) NOT NULL CHECK (btrim(name) <> ''),
    CONSTRAINT uq_screens_theatre_name UNIQUE (theatre_id, name)
);

CREATE TABLE tbooker.seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id BIGINT NOT NULL REFERENCES tbooker.screens (id),
    seat_number VARCHAR(20) NOT NULL CHECK (btrim(seat_number) <> ''),
    CONSTRAINT uq_seats_screen_number UNIQUE (screen_id, seat_number),
    -- Supports the composite FK that enforces a show seat's screen membership.
    CONSTRAINT uq_seats_id_screen UNIQUE (id, screen_id)
);

CREATE TABLE tbooker.movie_shows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES tbooker.movies (id),
    screen_id BIGINT NOT NULL REFERENCES tbooker.screens (id),
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_movie_shows_screen_start UNIQUE (screen_id, start_time),
    CONSTRAINT uq_movie_shows_id_screen UNIQUE (id, screen_id)
);
CREATE INDEX ix_movie_shows_movie ON tbooker.movie_shows (movie_id);
CREATE INDEX ix_movie_shows_start_id ON tbooker.movie_shows (start_time, id);

CREATE TABLE tbooker.show_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    -- Deliberate redundancy: both composite FKs must refer to the same screen.
    screen_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    CONSTRAINT ck_show_seats_status CHECK (status IN ('AVAILABLE', 'BOOKED')),
    CONSTRAINT uq_show_seats_show_seat UNIQUE (show_id, seat_id),
    CONSTRAINT fk_show_seats_show_screen FOREIGN KEY (show_id, screen_id)
        REFERENCES tbooker.movie_shows (id, screen_id),
    CONSTRAINT fk_show_seats_seat_screen FOREIGN KEY (seat_id, screen_id)
        REFERENCES tbooker.seats (id, screen_id)
);
CREATE INDEX ix_show_seats_seat_screen ON tbooker.show_seats (seat_id, screen_id);
