CREATE TABLE tbooker.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    show_seat_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES tbooker.users (id),
    CONSTRAINT fk_bookings_show_seat FOREIGN KEY (show_seat_id) REFERENCES tbooker.show_seats (id),
    CONSTRAINT uq_bookings_show_seat UNIQUE (show_seat_id),
    CONSTRAINT ck_bookings_status CHECK (status = 'CONFIRMED')
);
CREATE INDEX ix_bookings_user ON tbooker.bookings (user_id);
